### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by nlindblo** [svmironov/aircloud_ha#1]
Hello,

Thanks for starting this development, I am very keen on being able to control my Aircons through HA and get rid of that horrible Aircloud app. I have added the repo in HACS, the login details in configuration.yaml and restarted, but I am unable to see a climate entity. What am I missing here to complete the install and test this out ?

**Comment by svmironov** [comment]
Hi! Thank you for use it. 
You need use config 

configuration.yml:

air_cloud:
    email: "email"
    password: "password"
    
climate:
  - platform: air_cloud

lovelace object:
type: custom:simple-thermostat
entity: climate.kitchen_ac
header:  
  name: Kitchen AC
layout:  
mode:    
  headings: false

Entity IDs will load from airCloud

I tested it 5 minute ago. API is not reasonse and mobile Air Cloud app not working now. Probably after some time it will be work. I will follow the integration work

**Comment by nlindblo** [comment]
Thanks, I have the correct entries in configuration.yaml, but I also discovered that the app is not working as you said which is probably the root cause. I shall wait and see if it works when the service comes back online. I wish there was a way to operate these wifi adapters locally without having to use the AirCloud service...

**Comment by nlindblo** [comment]
So the API has come to life again and the installation completed with entities created, and it all looks great. However, i'm not able to turn the aircon on or off, if I change it to cool the card updates but nothing happens on the physical device and 60 seconds later the status is reset to "off". I was going to blame their flakey API, but interestingly enough the mobile app is quite snappy today and reacts on a turn on/off in 2-3 seconds.

Any ideas, is this working for you at the moment ?

**Comment by nlindblo** [comment]
Thanks,

The models I have are:

RAK-50RPE
RAK-25RPE
RAK-18RPE

If it helps, the bash script used by the this project https://github.com/lb544/ha-aircloud does work to turn on/off my aircons, though its missing other functionality that you have resolved.

**Comment by nlindblo** [comment]
Hello,

Unfortunately the API was down most of the day yesterday (as usual), but I have tested it today and receiving this message when toggling to "cool" to start the aircon

  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 980, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 497, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/air_cloud/climate.py", line 174, in set_hvac_mode
    self.__execute_command()
  File "/config/custom_components/air_cloud/climate.py", line 224, in __execute_command
    self._api.execute_command(self._id, self._power, self._target_temp, self._mode, self._fan_speed, self._fan_swing, self._humidity)
  File "/config/custom_components/air_cloud/api.py", line 62, in execute_command
    _LOGGER.debug("AirCloud command response: " + response)
TypeError: can only concatenate str (not "Response") to str

**Comment by nlindblo** [comment]
I have updated to 1.08 but it still doesn't seem to be working, and I'm not getting much in the logs either. Only entry I can find is this

````
2023-05-18 11:05:16.403 DEBUG (SyncWorker_4) [custom_components.air_cloud.api] AirCloud command response: <Response [400]>
````

I check the AirCloud app and API seem to be working OK today.

Is this currently working for you ? Anything else I can do to help troubleshoot, let me know please

**Comment by nlindblo** [comment]
Actually, I did a manual update of the humidity variable and set it to a static 50 and it started working again, if that can help you figure out what's wrong 

This works

````
def execute_command(self, id, power, idu_temperature, mode, fan_speed, fan_swing, humidity):
     self.__refresh_token()
      command = {"id": id, "power": power, "iduTemperature": idu_temperature, "mode": mode, "fanSpeed": fan_speed, "fanSwing": fan_swing, "humidity": 50}
      response = requests.put(API_HOST + CONTROL_URN + "/" + str(id) + "?familyId=" + str(self._family_id), headers=self.__create_headers(), json=command)
        _LOGGER.debug("AirCloud command response: " + str(response))
````

**Comment by svmironov** [comment]
I add more info for debug and remove id parameter it not needed. Status 400 is bad parameters in request. Now it works for me. But humidity parameter not work for my models

**Comment by nlindblo** [comment]
I have install 1.09 and I seem to be getting some more debug info in the logs now

````
{"notificationType":"ON_CONNECT","data":[{"serialNumber":"XXXX-XXXX-XXXX","iduFrostWashStatus":{"active":false,"priority":8,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"model":"HITACHI","id":5935,"vendorThingId":"JCH-886a232d","name":"Living Room","roomTemperature":22.0,"mode":"COOLING","iduTemperature":22.0,"humidity":126,"power":"OFF","relativeTemperature":0.0,"fanSpeed":"LV1","fanSwing":"BOTH","updatedAt":1684425850976,"specialOperationStatus":{"active":false,"priority":7,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"errorStatus":{"active":false,"priority":4,"lastUpdatedAt":0,"subCategory":"NO_ERROR","errorCode":null},"lastOnlineUpdatedAt":1683633040682,"scheduletype":"SCHEDULE_DISABLED","modelTypeId":155,"cloudId":"155_RAK-50RPE","opt4":0,"holidayModeStatus":{"active":false,"priority":0,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"online":true},{"serialNumber":"XXXX-XXXX-XXXX","iduFrostWashStatus":{"active":false,"priority":8,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"model":"HITACHI","id":5956,"vendorThingId":"JCH-886a2657","name":"Dining Room","roomTemperature":22.0,"mode":"AUTO","iduTemperature":0.0,"humidity":126,"power":"OFF","relativeTemperature":0.0,"fanSpeed":"AUTO","fanSwing":"OFF","updatedAt":1684352664110,"specialOperationStatus":{"active":false,"priority":7,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"errorStatus":{"active":false,"priority":4,"lastUpdatedAt":0,"subCategory":"NO_ERROR","errorCode":null},"lastOnlineUpdatedAt":1684219040162,"scheduletype":"SCHEDULE_DISABLED","modelTypeId":155,"cloudId":"155_RAK-25RPE","opt4":0,"holidayModeStatus":{"active":false,"priority":0,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"online":true},{"serialNumber":"XXXX-XXXX-XXXX","iduFrostWashStatus":{"active":false,"priority":8,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"model":"HITACHI","id":10819,"vendorThingId":"JCH-886a1ff8","name":"Office","roomTemperature":22.0,"mode":"COOLING","iduTemperature":18.0,"humidity":126,"power":"OFF","relativeTemperature":0.0,"fanSpeed":"AUTO","fanSwing":"BOTH","updatedAt":1684426200626,"specialOperationStatus":{"active":false,"priority":7,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"errorStatus":{"active":false,"priority":4,"lastUpdatedAt":0,"subCategory":"NO_ERROR","errorCode":null},"lastOnlineUpdatedAt":1684219052487,"scheduletype":"SCHEDULE_DISABLED","modelTypeId":155,"cloudId":"155_RAK-50RPE","opt4":0,"holidayModeStatus":{"active":false,"priority":0,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"online":true},{"serialNumber":"XXXX-XXXX-XXXX","iduFrostWashStatus":{"active":false,"priority":8,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"model":"HITACHI","id":5955,"vendorThingId":"JCH-886a1c6c","name":"Bedroom","roomTemperature":22.0,"mode":"AUTO","iduTemperature":0.0,"humidity":126,"power":"OFF","relativeTemperature":0.0,"fanSpeed":"AUTO","fanSwing":"OFF","updatedAt":1683923976587,"specialOperationStatus":{"active":false,"priority":7,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"errorStatus":{"active":false,"priority":4,"lastUpdatedAt":0,"subCategory":"NO_ERROR","errorCode":null},"lastOnlineUpdatedAt":1683926228511,"scheduletype":"SCHEDULE_DISABLED","modelTypeId":155,"cloudId":"155_RAK-18RPE","opt4":0,"holidayModeStatus":{"active":false,"priority":0,"lastUpdatedAt":0,"subCategory":null,"errorCode":null},"online":true}]}
2023-05-18 16:12:38.738 DEBUG (SyncWorker_4) [custom_components.air_cloud.api] AirCloud climate data: MESSAGE
destination:/notification/11125/11125
content-type:application/json;charset=UTF-8
subscription:666652ba-f0f0-41a8-9418-8c3f7c892fcb
message-id:3c1994d5-9484-9f67-8ae1-7a921c3d27c2-12203
content-length:3435
````

Note that humidity is 126, I think your code only sets it if <=100 (I am not a developer though..). So maybe this isn't a percent value ?

**Comment by svmironov** [comment]
For my models this value is always equal max integer. I don't know what those units are(

**Comment by nlindblo** [comment]
I think they are the standard hitachi line with the external wifi modules added, so I doubt this is an edge case even though they are different from yours. 

https://www.maison-energy.com/climatisation-R4/rak-50rpe-M113899.html

Would it be possible to make the value selectable or something just so it can be used by other models than the one you have ?

**Comment by nlindblo** [comment]
I upgraded to 1.10, still not working (sorry) and a new message in the log

````
2023-05-19 15:48:20.999 DEBUG (SyncWorker_8) [custom_components.air_cloud.api] AirCloud command response: b'{"type":"Fri May 19 15:48:20 GMT 2023","desc":"uri=/basic-idu-control/general-control-command/5935","stackTrace":"INVALID_HUMIDITY","code":null}'
````

**Comment by svmironov** [comment]
Is 50 humidity suitable for your model? May be create parameter in configuration with magic number?

**Comment by nlindblo** [comment]
Check out this article, maybe set it to 40 if it’s a static ? https://www.hitachiaircon.com/newsroom/en/news/what-s-the-ideal-indoor-humidity-and-how-can-it-be-managed

**Comment by svmironov** [comment]
I get error INVALID HUMIDITY for my models for any value not equal 0. Looking your log this value it not percent. Are you change it? What values work for you?

**Comment by nlindblo** [comment]
I have only tried ````"humidity": 50```` which works fine. Is there any way to check for the support of the humidity input and exclude if for your models ? 

- I have looked again in the AirCloud app and I can't see any way of setting the humidity there.

- I have tried a couple of manual starts of cooling, heating, drying from the air cloud app and if the debug info I see in HA is ````humidity: 126```` every time

**Comment by svmironov** [comment]
I'll do some weird logic) Perhaps in the future there will be statistics to correct this.

**Comment by nlindblo** [comment]
So the weird logic seemed to work and on/off is working OK now. There is a problem with the "Swing" though which I haven't had time to properly troubleshoot yet, I will open a new issue once I have some details to share
