### ISSUE TITLE
Target temperature not showing in mode Auto

### ISSUE THREAD

**Issue by nlindblo** [svmironov/aircloud_ha#10]
I noticed that the target temperature is not showing correctly in HA when the mode is set to Auto, if this can be looked at

![IMG_7BD0D8876B5C-1](https://github.com/svmironov/aircloud_ha/assets/9881339/8d49ea93-a1da-4bb7-98d5-8b0836c130fe)
<img width="577" alt="Screenshot 2023-10-31 at 09 46 31" src="https://github.com/svmironov/aircloud_ha/assets/9881339/d1d5e384-da14-4111-8a3f-e1e6c68658de">

**Comment by svmironov** [comment]
Unfortunately, I was unable to reproduce this bug.
