### ISSUE TITLE
aircloud...

### ISSUE THREAD

**Issue by bucolo** [svmironov/aircloud_ha#13]
Hello, sorry to post here but I don't really know where to go...
My aircloud go (the new aircloud home) does not work (and neither does the custom component). I retrieve the status but the commands do not work. Before it was slow, now it doesn't work at all. Is it the same for you ?

**Comment by svmironov** [comment]
Hi! Application aircloud go works like aircloud home for me

**Comment by bucolo** [comment]
Yes. It's ok for me too
Thanks
