### ISSUE TITLE
Интеграция с Алисой

### ISSUE THREAD

**Issue by Megard** [svmironov/aircloud_ha#16]
Добрый день
Спасибо, это единственный плагин под кондиционеры HITACHI который нормально у меня работает. Но есть проблема, при работе с Алисой через Yandex Smart Home у меня выскакивает ошибка "Что-то пошло не так попробуйте позднее", при этом команды проходят - кондиционер включается и выключается. Просьба посмотреть что можно сделать.

**Comment by svmironov** [comment]
Добрый день.
К сожалению у меня нет Алисы и я не могу это проверить, вероятно ошибка происходит из-за долго отклика. Я планирую переработать часть которая работает с API на асинхронные вызовы, скорее всего это исправит и эту проблему. Но не обещаю, что это произойдет быстро

**Comment by Megard** [comment]
Добрый день, понял, спасибо.

**Comment by svmironov** [comment]
Я добавил некоторые изменения, попробуйте обновить, возможно проблема будет устранена
