### ISSUE TITLE
HVAC_MODE_XXX was used from air_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.

### ISSUE THREAD

**Issue by Naraic88** [svmironov/aircloud_ha#17]
Hi,
First thank you for taking the time to make this integration. I tried adding it to my yaml file and got the following errors. 
Could this be related to the new HA update? 

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:205
Integration: Klima ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 19:52:59 (9 occurrences)
Last logged: 19:52:59

HVAC_MODE_HEAT was used from air_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/hcoohb/air_cloud_ha/issues
HVAC_MODE_OFF was used from air_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/hcoohb/air_cloud_ha/issues
SUPPORT_FAN_MODE was used from air_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/hcoohb/air_cloud_ha/issues
SUPPORT_SWING_MODE was used from air_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please create a bug report at https://github.com/hcoohb/air_cloud_ha/issues
SUPPORT_TARGET_TEMPERATURE was used from air_cloud, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/hcoohb/air_cloud_ha/issues

**Comment by Naraic88** [comment]
Before the warnings posted above i got: 

I am a bit new to HA. Have i done anything wrong with ex User and pw? 

Logger: homeassistant.setup
Source: setup.py:333
First occurred: 19:52:57 (1 occurrences)
Last logged: 19:52:57

Error during setup of component air_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/air_cloud/__init__.py", line 10, in async_setup
    login = config[DOMAIN].get(CONF_EMAIL)
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'NodeStrClass' object has no attribute 'get'

**Comment by Naraic88** [comment]
I also get this one that i have no clue how to adress.
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 09:50:33 (1 occurrences)
Last logged: 09:50:33

Setup failed for 'temp_adjust': Integration not found.

What could i be doing wrong?

**Comment by svmironov** [comment]
Hi! 
Thank for you report! I fixed warnings HVAC_MODE. Please update integration.
Your configuration will have been:

`air_cloud:`
    `email: "login" #supported only email authorization`
    `password: "pass"`

`climate:`
   `- platform: air_cloud`

Parameter 'temp_adjust' is optional.
