### ISSUE TITLE
Can't install new version

### ISSUE THREAD

**Issue by smi71** [svmironov/aircloud_ha#19]
I have got an error during update aircloud integration from v1.0.17 to v.2.0.1. "Empty filename". Than I uninstalled aircloud and tried install it again. 

1. added the repository to HACS
2. find aircloud
3. clicked the "Download" button than see endless downloading (rotating animation)
Check the logs and found next
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/base.py:686
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:57:09 (6 occurrences)
Last logged: 12:19:29

[140380568440768] Error handling message: Unknown error (unknown_error) mehome from 10.0.0.222 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 982, in async_install_repository
    await self.download_content()
  File "/config/custom_components/hacs/repositories/base.py", line 629, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 686, in download_repository_zip
    zip_file.extractall(self.content.path.local, extractable)
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1721, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1762, in _extract_member
    raise ValueError("Empty filename.")
ValueError: Empty filename.
```

**Comment by smi71** [comment]
> I have got an error during update aircloud integration from v1.0.17 to v.2.0.1. "Empty filename". Than I uninstalled aircloud and tried install it again.
> 
> 1. added the repository to HACS
> 2. find aircloud
> 3. clicked the "Download" button than see endless downloading (rotating animation)
>    Check the logs and found next
> 
> ```
> Logger: homeassistant.components.websocket_api.http.connection
> Source: custom_components/hacs/repositories/base.py:686
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 11:57:09 (6 occurrences)
> Last logged: 12:19:29
> 
> [140380568440768] Error handling message: Unknown error (unknown_error) mehome from 10.0.0.222 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
>     await func(hass, connection, msg)
>   File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
>     await repository.async_install()
>   File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
>     await self.async_install_repository()
>   File "/config/custom_components/hacs/repositories/base.py", line 982, in async_install_repository
>     await self.download_content()
>   File "/config/custom_components/hacs/repositories/base.py", line 629, in download_content
>     await self.download_repository_zip()
>   File "/config/custom_components/hacs/repositories/base.py", line 686, in download_repository_zip
>     zip_file.extractall(self.content.path.local, extractable)
>   File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1721, in extractall
>     self._extract_member(zipinfo, path, pwd)
>   File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1762, in _extract_member
>     raise ValueError("Empty filename.")
> ValueError: Empty filename.
> ```

В итоге я так и не понял в чем проблема. Установил вручную путем копирования файлов из архива в папку /config/custom_components/air_cloud и все заработало. Однако, скачивание по кнопке download так и не заработало.

**Comment by smi71** [comment]
Нашел корень проблемы. Обнаружил в логе
`2024-02-20 14:41:46.847 INFO (MainThread) [custom_components.hacs] <Integration svmironov/aircloud_ha> Trying experimental download`
[здесь](https://community.home-assistant.io/t/nibe-uplink-api-component-non-s-series/18173/708) прочитал, что причина всему этому -- включенная настройка  "Enable experimental features" в конфиге HACS. Выключил её и всё заработало.

**Comment by svmironov** [comment]
Спасибо, что отписали, а то уже проверил кучу разных вариантов но воспроизвести не получилось)
