### ISSUE TITLE
FAN mode not working

### ISSUE THREAD

**Issue by juju159** [svmironov/aircloud_ha#22]
Hello @svmironov ,
First of all, thank for the integration.
It works perfectly except the mode fan_only. It's not recognized by the devices. I have multiple Hitaschi (split) and I have the same behavior for all.

I use the model airhome 400 (wifi integrated) and spx-wfg02 (wifi adapter) adapter for one.

Best regards

**Comment by svmironov** [comment]
Hi! May be this module does not support this mode. Unfortunately, there is no way to get functions supported by the device through the API.

**Comment by juju159** [comment]
Hello @svmironov,

it works by setting  target_temp at 0, maybe it's possible to adapt climate object with a futur release?
Thanks.
Julien
Example:

`service: air_cloud.exec_command
metadata: {}
data:
  id: 42130
  power: "ON"
  target_temp: 0
  mode: FAN
  fan_speed: LV3
  fan_swing: AUTO
  humidity: 0`

**Comment by svmironov** [comment]
Ok! I added this fix to new release. Please update integration and test it.

**Comment by juju159** [comment]
Thanks I will test :)
