### ISSUE TITLE
Can't access shared heat pump

### ISSUE THREAD

**Issue by DisneyMikeNZ** [svmironov/aircloud_ha#24]
Hi there,

I've got a heat pump in my home that isn't paired directly with my account. Instead, it's "shared" with me [my account has been invited to control it], and it shows up in my airCloudGo app under a different "space".

This heat pump doesn't load into home assistant for some reason. Would you be able to have a look at this when you get a chance? Happy to provide screenshots if you need.

Thanks :)

**Comment by Warierke** [comment]
Same problem for shared AC's. Can't find them in home assistant.

**Comment by svmironov** [comment]
Hi! 
I added support for shared devices. Please update and test it.

**Comment by DisneyMikeNZ** [comment]
Thanks @svmironov - have updated and can confirm the fix works :)
