### ISSUE TITLE
Fan speeds

### ISSUE THREAD

**Issue by nlindblo** [svmironov/aircloud_ha#7]
Hi,

The Aircloud app has 4 different fan speeds (+ Auto as a 5th), but the HA integration only has 3 (High, Medium, Low). I would like to request that HA also gets the 4 speeds as selection for better granularity.

Thanks

**Comment by svmironov** [comment]
I added different fan speeds please test it

**Comment by nlindblo** [comment]
I have done some basic tests and it appears that 1-4 is working as expected, but when I select 5 nothing happens and the integration stops responding after until restarted. I can debug some more later today and see if the logs says anything, but just in case you wanted some quick feedback.

**Comment by svmironov** [comment]
There are 2 problems with this question. It is not possible to define model-specific functions. The HA has a limited of HomeKit compatible fan speed options. Please update to last version it fix this bug

**Comment by nlindblo** [comment]
I have updated and its working perfectly now, thanks for the quick turnaround !
