### ISSUE TITLE
Exemple confi.yaml

### ISSUE THREAD

**Issue by zicmu54** [svmironov/aircloud_ha#8]
Bonjour
Auriez-vous un exemple du fichier configuration.yaml pour rajouter les climatiseurs sur ha.
Cordialement.

**Comment by svmironov** [comment]
Ceci est un exemple de fichier de configuration

`air_cloud:
    email: "login" #supporté uniquement l'autorisation par e-mail
    password: "pass"

climate:
   - platform: air_cloud`

En plus du login et du mot de passe, vous n'avez besoin que des lignes

`climate:
   - platform: air_cloud`

Tout le reste sera téléchargé depuis le cloud
